package WyattWitemeyer.WarOfGillysburg;
public class EnemyDataBase {
	public static final Enemy GUARD = new CharacterBuilder()
			.Name("Guard")
			.Level(1)
			.Health(100)
			.Damage(25)
			.Armor(5)
			.ArmorPiercing(2)
			.Accuracy(90)
			.Block(5)
			.CriticalChance(2)
			.Speed(4)
			.AttackSpeed(5)
			.UseThreat(true)
			.buildE();
	
	public static final Enemy JAILOR = new CharacterBuilder()
			.Name("Jailor")
			.Level(4)
			.Health(150)
			.Damage(50)
			.Armor(7)
			.ArmorPiercing(3)
			.Accuracy(100)
			.Block(7)
			.CriticalChance(3)
			.Speed(5)
			.AttackSpeed(7)
			.UseThreat(false)
			.buildE();
	
	public static final Enemy MINION = new CharacterBuilder()
			.Name("Minion")
			.Level(1)
			.Health(50)
			.Damage(20)
			.Armor(3)
			.ArmorPiercing(2)
			.Accuracy(85)
			.Dodge(5)
			.CriticalChance(5)
			.Speed(7)
			.AttackSpeed(7)
			.UseThreat(true)
			.buildE();
	
	public static final Enemy HEXHAM_NOVIS_SWORDSMAN = new CharacterBuilder()
			.Name("Hexham Novice Swordsman")
			.Level(1)
			.Health(300)
			.Damage(80)
			.Armor(7)
			.ArmorPiercing(2)
			.Accuracy(100)
			.Block(15)
			.CriticalChance(10)
			.Speed(4)
			.AttackSpeed(6)
			.UseThreat(true)
			.buildE();
	
	public static final Enemy HEXHAM_ASSASSIN = new CharacterBuilder()
			.Name("Hexham Assassin")
			.Level(1)
			.Health(180)
			.Damage(115)
			.Armor(200)
			.ArmorPiercing(5)
			.Accuracy(110)
			.Dodge(20)
			.CriticalChance(12)
			.Speed(4)
			.AttackSpeed(6)
			.UseThreat(true)
			.buildE();
	
	public static final Enemy HEXHAM_ASSASSIN_LEADER = new CharacterBuilder()
			.Name("Hexham Assassin Leader")
			.Level(3)
			.Health(475+30)
			.Damage(165+15)
			.Armor(0)
			.ArmorPiercing(10)
			.Accuracy(120)
			.Dodge(25)
			.CriticalChance(15)
			.Speed(4)
			.AttackSpeed(8)
			.UseThreat(false)
			.buildE();
	
	public static final Enemy HEXHAM_SWORDSMAN = new CharacterBuilder()
			.Name("Hexham Swordsman")
			.Level(1)
			.Health(450)
			.Damage(100)
			.Armor(125)
			.ArmorPiercing(100)
			.Accuracy(115)
			.Block(18)
			.CriticalChance(12)
			.Speed(4)
			.AttackSpeed(7)
			.UseThreat(true)
			.buildE();
	
	public static final Enemy HEXHAM_ARCHER = new CharacterBuilder()
			.Name("Hexham Archer")
			.Level(1)
			.Health(350)
			.Damage(105)
			.Armor(110)
			.ArmorPiercing(120)
			.Accuracy(125)
			.Dodge(15)
			.CriticalChance(15)
			.Speed(4)
			.AttackSpeed(8)
			.UseThreat(true)
			.buildE();
	
	public static final Enemy HEXHAM_ROGUE = new CharacterBuilder()
			.Name("Hexham Rogue")
			.Level(1)
			.Health(300)
			.Damage(125)
			.Armor(100)
			.ArmorPiercing(130)
			.Accuracy(110)
			.Dodge(20)
			.CriticalChance(20)
			.Speed(6)
			.AttackSpeed(10)
			.UseThreat(true)
			.buildE();
	
	public static final Enemy ELITE_HEXHAM_GUARD = new CharacterBuilder()
			.Name("Elite Hexham Guard")
			.Level(3)
			.Health(750)
			.Damage(135)
			.Armor(150)
			.ArmorPiercing(120)
			.Accuracy(125)
			.Block(25)
			.CriticalChance(15)
			.Speed(3)
			.AttackSpeed(5)
			.UseThreat(false)
			.buildE();
	
	public static final Enemy TELEPORTER = new CharacterBuilder()
			.Name("Teleporter")
			.Health(575)
			.Armor(100)
			.UseThreat(false)
			.buildE();
	
	public static final Enemy LARGE_SPIDER = new CharacterBuilder()
			.Name("Large Spider")
			.Level(1)
			.Health(100)
			.Damage(10)
			.Armor(90)
			.ArmorPiercing(80)
			.Accuracy(100)
			.Dodge(15)
			.CriticalChance(0)
			.Speed(5)
			.AttackSpeed(11)
			.UseThreat(true)
			.buildE();
	
	public static final Enemy GIANT_SPIDER = new CharacterBuilder()
			.Name("Giant Spider")
			.Level(1)
			.Health(175)
			.Damage(25)
			.Armor(95)
			.ArmorPiercing(85)
			.Accuracy(105)
			.Dodge(10)
			.CriticalChance(5)
			.Speed(4)
			.AttackSpeed(11)
			.UseThreat(true)
			.buildE();
	
	public static final Enemy GIANT_SCORPION = new CharacterBuilder()
			.Name("Giant Scorpion")
			.Level(1)
			.Health(230)
			.Damage(20)
			.Armor(115)
			.ArmorPiercing(80)
			.Accuracy(105)
			.Dodge(15)
			.CriticalChance(3)
			.Speed(4)
			.AttackSpeed(8)
			.UseThreat(true)
			.buildE();
	
	public static final Enemy WASP_SWARM = new CharacterBuilder()
			.Name("Wasp Swarm")
			.Level(1)
			.Health(150)
			.Damage(25)
			.Armor(95)
			.ArmorPiercing(90)
			.Accuracy(90)
			.Dodge(30)
			.CriticalChance(7)
			.Speed(5)
			.AttackSpeed(10)
			.UseThreat(true)
			.buildE();
	
	public static final Enemy MAGICAL_MONSTER = new CharacterBuilder()
			.Name("Magical Monster")
			.Level(1)
			.Health(250)
			.Damage(65)
			.Armor(95)
			.ArmorPiercing(105)
			.Accuracy(100)
			.Dodge(28)
			.CriticalChance(8)
			.Speed(7)
			.AttackSpeed(15)
			.UseThreat(true)
			.buildE();
}
